# Travis CI Configuration
# https://docs.travis-ci.com
# This file is based on
# TravisCI · koalaman/shellcheck Wiki
# https://github.com/koalaman/shellcheck/wiki/TravisCI
## Use container-based infrastructure for quicker build start-up
sudo: false

## We only support Ubuntu 14.04 and newer
dist: trusty

language: bash

## EXPERIMENTAL
## Customizing the Build - Travis CI
## https://docs.travis-ci.com/user/customizing-the-build/#Git-Clone-Depth
## > Please note that if you use a depth of 1 and have a queue of jobs, Travis CI won’t build commits that are in the queue when you push a new commit.
git:
  submodules: false
  depth: 1

addons:
  apt:
    packages:
    - realpath      # Merged to GNU Coreutils in Ubuntu 16.04

before_install:
- git submodule init 'Continuous Integration/Utilities for Travis CI'
- git submodule update --depth=30

install:
- ./"Continuous Integration/Utilities for Travis CI/Setup ShellCheck's Latest Release without Re-building.bash"
- PATH="${HOME}/Software/shellcheck-stable:${PATH}"
- which -a shellcheck
- shellcheck --version

- pip install --user pre-commit

before_script:
- git diff-tree -z --no-commit-id --name-only -r HEAD | xargs --null pre-commit run --files

script: true

cache:
  directories:
  - $HOME/Software

matrix:
  fast_finish: true
